quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.max-size=20
quarkus.datasource.reactive.cache-prepared-statements=true
quarkus.datasource.devservices.init-script-path=db/init/01-schema.sql

quarkus.banner.enabled=false
quarkus.log.level=WARN
quarkus.log.category."com.product".level=INFO
quarkus.log.category."com.github.benmanes.caffeine.cache.LocalAsyncCache".level=ERROR

quarkus.native.additional-build-args=--gc=serial
